spring.application.name=reservation-backend
spring.datasource.url=jdbc:postgresql://localhost:5433/reservation
# ---------------------------
spring.datasource.username=postgres
spring.datasource.password=${DB_Pass_Postgre-mysql}
# ---------------------------
spring.jpa.show-sql=true
# ---------------------------
# permite el mapeo automatico de las entidades y las crea en la BDD
spring.jpa.hibernate.ddl-auto=update
# ---------------------------
soring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
logging.pattern.console=%-5level %logger{36} - %msg%n
logging.exception-conversion-word=%wEx
logging.level.root=INFO